// <auto-generated />
namespace CrmBl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class update120420 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update120420));
        
        string IMigrationMetadata.Id
        {
            get { return "202004120022022_update120420"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
